/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.llslucas.condominio.view;

import br.llslucas.condominio.controller.FaturaController;
import br.llslucas.condominio.controller.ResidenciaController;
import br.llslucas.condominio.model.Fatura;
import br.llslucas.condominio.model.Residencia;
import java.awt.CardLayout;
import java.sql.Date;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Lucas
 */
public class CadastraFaturasView extends javax.swing.JPanel {

  private final ResidenciaController residenciaController;
  private final FaturaController faturaController;

  /**
   * Creates new form CondominioView
   *
   * @param residenciaController
   * @param faturaController
   */
  public CadastraFaturasView(ResidenciaController residenciaController, FaturaController faturaController) {
    initComponents();
    this.residenciaController = residenciaController;
    this.faturaController = faturaController;
  }

  @Override
  public void setVisible(boolean aFlag) {
    super.setVisible(aFlag);
    if (aFlag) {
      fResidencia.removeAllItems();

      try {
	this.residenciaController.list().forEach((i, residencia) -> {
	  fResidencia.addItem(residencia);
	});
      } catch (Exception ex) {
	JOptionPane.showMessageDialog(this, "Falha na conexão com o banco de dados", "Erro", JOptionPane.ERROR_MESSAGE);
      }
    }
  }

  private void close() {
    JPanel parent = (JPanel) this.getParent();
    CardLayout layout = (CardLayout) parent.getLayout();
    layout.show(parent, "faturas");
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    fValor = new javax.swing.JFormattedTextField();
    lValor = new javax.swing.JLabel();
    fVencimento = new javax.swing.JFormattedTextField();
    lVencimento = new javax.swing.JLabel();
    fResidencia = new javax.swing.JComboBox<>();
    lResidencia = new javax.swing.JLabel();
    jPanel2 = new javax.swing.JPanel();
    btnCadastrar = new javax.swing.JButton();
    btnSair = new javax.swing.JButton();

    setPreferredSize(new java.awt.Dimension(860, 547));

    jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro de Morador"));

    fValor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
    fValor.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        fValorActionPerformed(evt);
      }
    });

    lValor.setText("Valor");

    try {
      fVencimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
    } catch (java.text.ParseException ex) {
      ex.printStackTrace();
    }

    lVencimento.setText("Data de Vencimento");

    lResidencia.setText("Residencia");

    btnCadastrar.setText("Cadastrar");
    btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnCadastrarActionPerformed(evt);
      }
    });

    btnSair.setText("Sair");
    btnSair.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnSairActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addComponent(btnCadastrar)
        .addGap(30, 30, 30)
        .addComponent(btnSair))
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addGap(0, 0, Short.MAX_VALUE)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnCadastrar)
          .addComponent(btnSair)))
    );

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap(606, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
            .addGap(50, 50, 50)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(fValor, javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(fVencimento, javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(fResidencia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(lValor)
                  .addComponent(lVencimento)
                  .addComponent(lResidencia))
                .addGap(0, 0, Short.MAX_VALUE)))))
        .addGap(50, 50, 50))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(20, 20, 20)
        .addComponent(lValor)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(fValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(20, 20, 20)
        .addComponent(lVencimento)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(fVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(20, 20, 20)
        .addComponent(lResidencia)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(fResidencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 267, Short.MAX_VALUE)
        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(30, 30, 30))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );
  }// </editor-fold>//GEN-END:initComponents

  private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
    Double valor = Double.valueOf(fValor.getText().replace(",", "."));
    Date vencimento = Date.valueOf(LocalDate.parse(fVencimento.getText(), DateTimeFormatter.ofPattern("dd/MM/yyyy")).toString());
    Residencia residencia = (Residencia) fResidencia.getSelectedItem();
    
    if(residencia.getProprietarioId() == null){
      JOptionPane.showMessageDialog(this, "Não é possível gerar cobrança de uma casa que não possui proprietário.", "Erro", JOptionPane.ERROR_MESSAGE);
      return;
    }
    
    Fatura fatura = new Fatura(valor, vencimento, residencia.getId(), residencia.getProprietarioId());
    
    try {
      this.faturaController.create(fatura);
      JOptionPane.showMessageDialog(this, "Fatura cadastrado com sucesso!");
      fValor.setText("");
      fVencimento.setText("");
      fResidencia.setSelectedIndex(-1);
      close();
    } catch (Exception ex) {
      JOptionPane.showMessageDialog(this, "Falha ao cadastrar fatura, verifique o erro abaixo: \n" + ex.getMessage());
    }

  }//GEN-LAST:event_btnCadastrarActionPerformed

  private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
    close();
  }//GEN-LAST:event_btnSairActionPerformed

  private void fValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fValorActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_fValorActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnCadastrar;
  private javax.swing.JButton btnSair;
  private javax.swing.JComboBox<Residencia> fResidencia;
  private javax.swing.JFormattedTextField fValor;
  private javax.swing.JFormattedTextField fVencimento;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JLabel lResidencia;
  private javax.swing.JLabel lValor;
  private javax.swing.JLabel lVencimento;
  // End of variables declaration//GEN-END:variables
}
