/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.llslucas.condominio.view;

import br.llslucas.condominio.controller.CondominioController;
import br.llslucas.condominio.controller.MoradorController;
import br.llslucas.condominio.controller.ResidenciaController;
import br.llslucas.condominio.model.Condominio;
import br.llslucas.condominio.model.Morador;
import br.llslucas.condominio.model.Residencia;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Lucas
 */
public class EditaResidenciasView extends javax.swing.JPanel {

  private final CondominioController condominioController;
  private final ResidenciaController residenciaController;
  private final MoradorController moradorController;

  private static Long residenciaId = null;

  /**
   * Creates new form CondominioView
   *
   * @param condominioController
   * @param residenciaController
   * @param moradorController
   */
  public EditaResidenciasView(CondominioController condominioController, ResidenciaController residenciaController, MoradorController moradorController) {
    initComponents();
    this.condominioController = condominioController;
    this.residenciaController = residenciaController;
    this.moradorController = moradorController;
  }

  public static void setId(Long id) {
    residenciaId = id;
  }

  @Override
  public void setVisible(boolean aFlag) {
    super.setVisible(aFlag);

    if (aFlag) {
      if (residenciaId != null) {
	try {
	  Residencia residencia = residenciaController.getById(residenciaId);

	  fRua.setText(residencia.getRua());
	  fNumero.setText(residencia.getNumero().toString());
	  fCep.setText(residencia.getCep());
	  fTipo.setText(residencia.getTipo());

	  Morador proprietario;
	  if (residencia.getProprietarioId() != null) {
	    proprietario = moradorController.getById(residencia.getProprietarioId());
	  } else {
	    proprietario = null;
	  }

	  Condominio condominio = condominioController.getById(residencia.getCondominioId());

	  fProprietario.removeAllItems();
	  fProprietario.addItem(null);
	  this.moradorController.list().forEach((i, morador) -> {
	    fProprietario.addItem(morador);
	  });
	  fProprietario.setSelectedItem(proprietario);

	  fCondominio.removeAllItems();
	  this.condominioController.list().forEach((i, cond) -> {
	    fCondominio.addItem(cond);
	  });
	  fCondominio.setSelectedItem(condominio);

	} catch (Exception ex) {
	  JOptionPane.showMessageDialog(this, "Falha na conexão com o banco de dados", "Erro", JOptionPane.ERROR_MESSAGE);
	  super.setVisible(false);
	}
      } else {
	JOptionPane.showMessageDialog(this, "Nenhuma residência foi selecionada.", "Erro", JOptionPane.ERROR_MESSAGE);
      }
    } else {
      residenciaId = null;
      fRua.setText("");
      fNumero.setText("");
      fCep.setText("");
      fTipo.setText("");
      fProprietario.setSelectedIndex(-1);
      fCondominio.setSelectedIndex(-1);
    }
  }

  private void close() {
    JPanel parent = (JPanel) this.getParent();
    CardLayout layout = (CardLayout) parent.getLayout();
    layout.show(parent, "residencias");
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    fRua = new javax.swing.JTextField();
    lRua = new javax.swing.JLabel();
    fNumero = new javax.swing.JTextField();
    lNumero = new javax.swing.JLabel();
    fCep = new javax.swing.JTextField();
    lCep = new javax.swing.JLabel();
    fTipo = new javax.swing.JTextField();
    lTipo = new javax.swing.JLabel();
    fProprietario = new javax.swing.JComboBox<>();
    lProprietario = new javax.swing.JLabel();
    fCondominio = new javax.swing.JComboBox<>();
    lCondominio = new javax.swing.JLabel();
    jPanel2 = new javax.swing.JPanel();
    btnCadastrar = new javax.swing.JButton();
    btnSair = new javax.swing.JButton();

    setPreferredSize(new java.awt.Dimension(860, 547));

    jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Edição de Residência"));

    lRua.setText("Rua");

    lNumero.setText("Numero");

    lCep.setText("CEP");

    lTipo.setText("Tipo");

    lProprietario.setText("Proprietario");

    lCondominio.setText("Condominio");

    btnCadastrar.setText("Salvar");
    btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnCadastrarActionPerformed(evt);
      }
    });

    btnSair.setText("Sair");
    btnSair.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnSairActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addComponent(btnCadastrar)
        .addGap(30, 30, 30)
        .addComponent(btnSair))
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addGap(0, 0, Short.MAX_VALUE)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnCadastrar)
          .addComponent(btnSair)))
    );

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap(614, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
            .addGap(50, 50, 50)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(fCondominio, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(fRua)
              .addComponent(fNumero)
              .addComponent(fCep)
              .addComponent(fTipo)
              .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(lRua)
                  .addComponent(lNumero)
                  .addComponent(lCep)
                  .addComponent(lTipo)
                  .addComponent(lProprietario)
                  .addComponent(lCondominio))
                .addGap(0, 0, Short.MAX_VALUE))
              .addComponent(fProprietario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        .addGap(50, 50, 50))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(20, 20, 20)
        .addComponent(lRua)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(fRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(20, 20, 20)
        .addComponent(lNumero)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(fNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(20, 20, 20)
        .addComponent(lCep)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(fCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(20, 20, 20)
        .addComponent(lTipo)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(fTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(20, 20, 20)
        .addComponent(lProprietario)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(fProprietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(20, 20, 20)
        .addComponent(lCondominio)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(fCondominio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(30, 30, 30))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );
  }// </editor-fold>//GEN-END:initComponents

  private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
    String rua = fRua.getText();
    Long numero = Long.parseLong(fNumero.getText());
    String cep = fCep.getText();
    String tipo = fTipo.getText();
    Morador proprietario = (Morador) fProprietario.getSelectedItem();
    Long proprietarioId = proprietario != null ? proprietario.getId() : null;

    Long condominioId = ((Condominio) fCondominio.getSelectedItem()).getId();

    Residencia condominio = new Residencia(residenciaId, rua, numero, cep, tipo, proprietarioId, condominioId);

    try {
      this.residenciaController.update(condominio);
      JOptionPane.showMessageDialog(this, "Residência alterada com sucesso!");
      fRua.setText("");
      fNumero.setText("");
      fCep.setText("");
      fTipo.setText("");
      fProprietario.setSelectedIndex(-1);
      fCondominio.setSelectedIndex(-1);
      close();
    } catch (Exception ex) {
      JOptionPane.showMessageDialog(this, "Falha ao alterar residência, verifique o erro abaixo: \n" + ex.getMessage());
    }

  }//GEN-LAST:event_btnCadastrarActionPerformed

  private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
    close();
  }//GEN-LAST:event_btnSairActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnCadastrar;
  private javax.swing.JButton btnSair;
  private javax.swing.JTextField fCep;
  private javax.swing.JComboBox<Condominio> fCondominio;
  private javax.swing.JTextField fNumero;
  private javax.swing.JComboBox<Morador> fProprietario;
  private javax.swing.JTextField fRua;
  private javax.swing.JTextField fTipo;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JLabel lCep;
  private javax.swing.JLabel lCondominio;
  private javax.swing.JLabel lNumero;
  private javax.swing.JLabel lProprietario;
  private javax.swing.JLabel lRua;
  private javax.swing.JLabel lTipo;
  // End of variables declaration//GEN-END:variables
}
