/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.llslucas.condominio.view;

import br.llslucas.condominio.controller.MoradorController;
import br.llslucas.condominio.controller.ResidenciaController;
import br.llslucas.condominio.model.Morador;
import br.llslucas.condominio.model.Residencia;
import java.awt.CardLayout;
import java.sql.Date;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Lucas
 */
public class EditaMoradoresView extends javax.swing.JPanel {

  ResidenciaController residenciaController;
  MoradorController moradorController;

  public static Long idMorador = null;

  /**
   * Creates new form CondominioView
   *
   * @param residenciaController
   * @param moradorController
   */
  public EditaMoradoresView(ResidenciaController residenciaController, MoradorController moradorController) {
    initComponents();
    this.residenciaController = residenciaController;
    this.moradorController = moradorController;
  }

  public static void setId(Long id) {
    idMorador = id;
  }

  @Override
  public void setVisible(boolean aFlag) {
    super.setVisible(aFlag);
    if (aFlag) {
      if (idMorador != null) {
	try {
	  Morador morador = moradorController.getById(idMorador);

	  fNome.setText(morador.getNome());
	  fNascimento.setText(morador.getDataNascimento().toLocalDate().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));
	  fRG.setText(morador.getRg());
	  fCPF.setText(morador.getCpf());

	  Residencia residencia;
	  if (morador.getResidenciaId() != null) {
	    residencia = residenciaController.getById(morador.getResidenciaId());
	  } else {
	    residencia = null;
	  }

	  fResidencia.removeAllItems();

	  this.residenciaController.list().forEach((i, res) -> {
	    fResidencia.addItem(res);
	  });
	} catch (Exception ex) {
	  JOptionPane.showMessageDialog(this, "Falha na conexão com o banco de dados", "Erro", JOptionPane.ERROR_MESSAGE);
	}
      } else {
	JOptionPane.showMessageDialog(this, "Nenhum morador foi selecionado.", "Erro", JOptionPane.ERROR_MESSAGE);
      }
    } else {
      idMorador = null;
      fNome.setText("");
      fNascimento.setText("");
      fRG.setText("");
      fCPF.setText("");
      fResidencia.setSelectedIndex(-1);
    }
  }

  private void close() {
    JPanel parent = (JPanel) this.getParent();
    CardLayout layout = (CardLayout) parent.getLayout();
    layout.show(parent, "moradores");
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    fNome = new javax.swing.JTextField();
    lNome = new javax.swing.JLabel();
    fNascimento = new javax.swing.JFormattedTextField();
    lNascimento = new javax.swing.JLabel();
    fRG = new javax.swing.JTextField();
    lRG = new javax.swing.JLabel();
    fCPF = new javax.swing.JTextField();
    lCPF = new javax.swing.JLabel();
    fResidencia = new javax.swing.JComboBox<>();
    lResidencia = new javax.swing.JLabel();
    jPanel2 = new javax.swing.JPanel();
    btnSalvar = new javax.swing.JButton();
    btnSair = new javax.swing.JButton();

    setPreferredSize(new java.awt.Dimension(860, 547));

    jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Edição de Morador"));

    lNome.setText("Nome");

    try {
      fNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
    } catch (java.text.ParseException ex) {
      ex.printStackTrace();
    }

    lNascimento.setText("Data de Nascimento");

    lRG.setText("RG");

    lCPF.setText("CPF");

    lResidencia.setText("Residencia");

    btnSalvar.setText("Salver");
    btnSalvar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnSalvarActionPerformed(evt);
      }
    });

    btnSair.setText("Sair");
    btnSair.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnSairActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addComponent(btnSalvar)
        .addGap(30, 30, 30)
        .addComponent(btnSair))
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addGap(0, 0, Short.MAX_VALUE)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnSalvar)
          .addComponent(btnSair)))
    );

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap(614, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
            .addGap(50, 50, 50)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(fNascimento, javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(fNome)
              .addComponent(fRG)
              .addComponent(fCPF)
              .addComponent(fResidencia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(lNome)
                  .addComponent(lNascimento)
                  .addComponent(lRG)
                  .addComponent(lCPF)
                  .addComponent(lResidencia))
                .addGap(0, 0, Short.MAX_VALUE)))))
        .addGap(50, 50, 50))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(20, 20, 20)
        .addComponent(lNome)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(fNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(20, 20, 20)
        .addComponent(lNascimento)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(fNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(20, 20, 20)
        .addComponent(lRG)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(fRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(20, 20, 20)
        .addComponent(lCPF)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(fCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(20, 20, 20)
        .addComponent(lResidencia)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(fResidencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(30, 30, 30))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );
  }// </editor-fold>//GEN-END:initComponents

  private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
    String nome = fNome.getText();
    Date dataNascimento = Date.valueOf(LocalDate.parse(fNascimento.getText(), DateTimeFormatter.ofPattern("dd/MM/yyyy")).toString());
    String rg = fRG.getText();
    String cpf = fCPF.getText();
    Residencia residencia = (Residencia) fResidencia.getSelectedItem();

    Morador morador = new Morador(idMorador, nome, dataNascimento, rg, cpf, residencia.getId());

    try {
      this.moradorController.update(morador);
      JOptionPane.showMessageDialog(this, "Morador alterado com sucesso!");
      fNome.setText("");
      fNascimento.setText("");
      fRG.setText("");
      fCPF.setText("");
      fResidencia.setSelectedIndex(-1);
      close();
    } catch (Exception ex) {
      JOptionPane.showMessageDialog(this, "Falha ao alterar morador, verifique o erro abaixo: \n" + ex.getMessage());
    }

  }//GEN-LAST:event_btnSalvarActionPerformed

  private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
    close();
  }//GEN-LAST:event_btnSairActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnSair;
  private javax.swing.JButton btnSalvar;
  private javax.swing.JTextField fCPF;
  private javax.swing.JFormattedTextField fNascimento;
  private javax.swing.JTextField fNome;
  private javax.swing.JTextField fRG;
  private javax.swing.JComboBox<Residencia> fResidencia;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JLabel lCPF;
  private javax.swing.JLabel lNascimento;
  private javax.swing.JLabel lNome;
  private javax.swing.JLabel lRG;
  private javax.swing.JLabel lResidencia;
  // End of variables declaration//GEN-END:variables
}
