/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.llslucas.condominio.view;

import br.llslucas.condominio.controller.CondominioController;
import br.llslucas.condominio.controller.FaturaController;
import br.llslucas.condominio.controller.MoradorController;
import br.llslucas.condominio.controller.ResidenciaController;
import br.llslucas.condominio.persistence.DAOClient;
import br.llslucas.condominio.persistence.factory.MySqlDAOFactory;
import java.awt.CardLayout;

/**
 *
 * @author Lucas
 */
public class MainView extends javax.swing.JFrame {

  private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainView.class.getName());

  /**
   * Creates new form MainView
   */
  public MainView() {
    initComponents();
    setLocationRelativeTo(null);

    MySqlDAOFactory daoFactory = new MySqlDAOFactory();
    DAOClient dao = new DAOClient(daoFactory);

    CondominioController condominioController = new CondominioController(dao);
    ResidenciaController residenciaController = new ResidenciaController(dao);
    MoradorController moradorController = new MoradorController(dao);
    FaturaController faturaController = new FaturaController(dao);

    contentPanel.add(new HomeView(), "home");

    contentPanel.add(new CondominiosView(condominioController), "condominios");
    contentPanel.add(new CadastraCondominiosView(condominioController), "cadastroCondominios");
    contentPanel.add(new EditaCondominiosView(condominioController), "editarCondominios");

    contentPanel.add(new ResidenciasView(condominioController, residenciaController, moradorController, faturaController), "residencias");
    contentPanel.add(new CadastraResidenciasView(condominioController, residenciaController, moradorController), "cadastroResidencias");
    contentPanel.add(new EditaResidenciasView(condominioController, residenciaController, moradorController), "editarResidencias");

    contentPanel.add(new MoradoresView(residenciaController, moradorController), "moradores");
    contentPanel.add(new CadastraMoradoresView(residenciaController, moradorController), "cadastroMoradores");
    contentPanel.add(new EditaMoradoresView(residenciaController, moradorController), "editarMoradores");

    contentPanel.add(new FaturasView(residenciaController, moradorController, faturaController), "faturas");
    contentPanel.add(new CadastraFaturasView(residenciaController, faturaController), "cadastroFaturas");

    CardLayout layout = (CardLayout) contentPanel.getLayout();
    layout.show(contentPanel, "home");
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    contentPanel = new javax.swing.JPanel();
    menuBar = new javax.swing.JMenuBar();
    btnOptions = new javax.swing.JMenu();
    btnClose = new javax.swing.JMenuItem();
    btnCondominios = new javax.swing.JMenu();
    btnShowCondominios = new javax.swing.JMenuItem();
    btnCadastrarCondominio = new javax.swing.JMenuItem();
    btnResidencias = new javax.swing.JMenu();
    btnShowResidencias = new javax.swing.JMenuItem();
    btnCadastrarResidencias = new javax.swing.JMenuItem();
    btnMoradores = new javax.swing.JMenu();
    btnShowMoradores = new javax.swing.JMenuItem();
    btnCadastrarMoradores = new javax.swing.JMenuItem();
    btnFaturas = new javax.swing.JMenu();
    btnShowFaturas = new javax.swing.JMenuItem();
    btnCadastrarFaturas = new javax.swing.JMenuItem();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setMinimumSize(new java.awt.Dimension(860, 600));
    setPreferredSize(new java.awt.Dimension(860, 600));
    setResizable(false);

    contentPanel.setLayout(new java.awt.CardLayout());

    menuBar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

    btnOptions.setText("Opções");
    btnOptions.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

    btnClose.setText("Sair");
    btnClose.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnCloseActionPerformed(evt);
      }
    });
    btnOptions.add(btnClose);

    menuBar.add(btnOptions);

    btnCondominios.setText("Condomínios");
    btnCondominios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

    btnShowCondominios.setText("Listar");
    btnShowCondominios.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnShowCondominiosActionPerformed(evt);
      }
    });
    btnCondominios.add(btnShowCondominios);

    btnCadastrarCondominio.setText("Cadastrar");
    btnCadastrarCondominio.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnCadastrarCondominioActionPerformed(evt);
      }
    });
    btnCondominios.add(btnCadastrarCondominio);

    menuBar.add(btnCondominios);

    btnResidencias.setText("Residências");
    btnResidencias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

    btnShowResidencias.setText("Listar");
    btnShowResidencias.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnShowResidenciasActionPerformed(evt);
      }
    });
    btnResidencias.add(btnShowResidencias);

    btnCadastrarResidencias.setText("Cadastrar");
    btnCadastrarResidencias.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnCadastrarResidenciasActionPerformed(evt);
      }
    });
    btnResidencias.add(btnCadastrarResidencias);

    menuBar.add(btnResidencias);

    btnMoradores.setText("Moradores");
    btnMoradores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

    btnShowMoradores.setText("Listar");
    btnShowMoradores.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnShowMoradoresActionPerformed(evt);
      }
    });
    btnMoradores.add(btnShowMoradores);

    btnCadastrarMoradores.setText("Cadastrar");
    btnCadastrarMoradores.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnCadastrarMoradoresActionPerformed(evt);
      }
    });
    btnMoradores.add(btnCadastrarMoradores);

    menuBar.add(btnMoradores);

    btnFaturas.setText("Faturas");
    btnFaturas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

    btnShowFaturas.setText("Listar");
    btnShowFaturas.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnShowFaturasActionPerformed(evt);
      }
    });
    btnFaturas.add(btnShowFaturas);

    btnCadastrarFaturas.setText("Cadastrar");
    btnCadastrarFaturas.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnCadastrarFaturasActionPerformed(evt);
      }
    });
    btnFaturas.add(btnCadastrarFaturas);

    menuBar.add(btnFaturas);

    setJMenuBar(menuBar);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 860, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
    System.exit(0);
  }//GEN-LAST:event_btnCloseActionPerformed

  private void btnShowCondominiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowCondominiosActionPerformed
    CardLayout layout = (CardLayout) contentPanel.getLayout();
    layout.show(contentPanel, "condominios");
  }//GEN-LAST:event_btnShowCondominiosActionPerformed

  private void btnCadastrarCondominioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarCondominioActionPerformed
    CardLayout layout = (CardLayout) contentPanel.getLayout();
    layout.show(contentPanel, "cadastroCondominios");
  }//GEN-LAST:event_btnCadastrarCondominioActionPerformed

  private void btnShowResidenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowResidenciasActionPerformed
    CardLayout layout = (CardLayout) contentPanel.getLayout();
    layout.show(contentPanel, "residencias");
  }//GEN-LAST:event_btnShowResidenciasActionPerformed

  private void btnCadastrarResidenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarResidenciasActionPerformed
    CardLayout layout = (CardLayout) contentPanel.getLayout();
    layout.show(contentPanel, "cadastroResidencias");
  }//GEN-LAST:event_btnCadastrarResidenciasActionPerformed

  private void btnShowMoradoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowMoradoresActionPerformed
    CardLayout layout = (CardLayout) contentPanel.getLayout();
    layout.show(contentPanel, "moradores");
  }//GEN-LAST:event_btnShowMoradoresActionPerformed

  private void btnCadastrarMoradoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarMoradoresActionPerformed
    CardLayout layout = (CardLayout) contentPanel.getLayout();
    layout.show(contentPanel, "cadastroMoradores");
  }//GEN-LAST:event_btnCadastrarMoradoresActionPerformed

  private void btnShowFaturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowFaturasActionPerformed
    CardLayout layout = (CardLayout) contentPanel.getLayout();
    layout.show(contentPanel, "faturas");
  }//GEN-LAST:event_btnShowFaturasActionPerformed

  private void btnCadastrarFaturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarFaturasActionPerformed
    CardLayout layout = (CardLayout) contentPanel.getLayout();
    layout.show(contentPanel, "cadastroFaturas");
  }//GEN-LAST:event_btnCadastrarFaturasActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
	if ("Nimbus".equals(info.getName())) {
	  javax.swing.UIManager.setLookAndFeel(info.getClassName());
	  break;
	}
      }
    } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
      logger.log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> new MainView().setVisible(true));
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JMenuItem btnCadastrarCondominio;
  private javax.swing.JMenuItem btnCadastrarFaturas;
  private javax.swing.JMenuItem btnCadastrarMoradores;
  private javax.swing.JMenuItem btnCadastrarResidencias;
  private javax.swing.JMenuItem btnClose;
  private javax.swing.JMenu btnCondominios;
  private javax.swing.JMenu btnFaturas;
  private javax.swing.JMenu btnMoradores;
  private javax.swing.JMenu btnOptions;
  private javax.swing.JMenu btnResidencias;
  private javax.swing.JMenuItem btnShowCondominios;
  private javax.swing.JMenuItem btnShowFaturas;
  private javax.swing.JMenuItem btnShowMoradores;
  private javax.swing.JMenuItem btnShowResidencias;
  private javax.swing.JPanel contentPanel;
  private javax.swing.JMenuBar menuBar;
  // End of variables declaration//GEN-END:variables
}
