/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.llslucas.condominio.view;

import br.llslucas.condominio.controller.MoradorController;
import br.llslucas.condominio.controller.ResidenciaController;
import br.llslucas.condominio.model.Morador;
import br.llslucas.condominio.model.Residencia;
import java.awt.CardLayout;
import java.sql.Date;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.event.TableModelEvent;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lucas
 */
public class MoradoresView extends javax.swing.JPanel {

  private final ResidenciaController residenciaController;
  private final MoradorController moradorController;

  private static Long residenciaIdFilter = null;

  /**
   * Creates new form ResidenciaView
   *
   * @param residenciaController
   * @param moradorController
   */
  public MoradoresView(ResidenciaController residenciaController, MoradorController moradorController) {
    initComponents();
    this.residenciaController = residenciaController;
    this.moradorController = moradorController;

    DefaultTableModel model = (DefaultTableModel) table.getModel();
    model.addTableModelListener(evento -> {
      if (evento.getType() == TableModelEvent.UPDATE) {
	this.updateRow();
      }
    });
  }

  @Override
  public void setVisible(boolean aFlag) {
    super.setVisible(aFlag);

    if (aFlag) {
      preencherTabela();
    } else {
      residenciaIdFilter = null;
    }
  }

  public void updateRow() {
    int row = table.getSelectedRow();

    if (row == -1) {
      return;
    }

    Date dataNascimento;

    try {
      dataNascimento = Date.valueOf(LocalDate.parse((String) table.getValueAt(row, 2), DateTimeFormatter.ofPattern("dd/MM/yyyy")).toString());
    } catch (Exception ex) {
      JOptionPane.showMessageDialog(this, "Data em formato incorreto (dd/MM/yyyy)", "Erro", JOptionPane.ERROR_MESSAGE);
      preencherTabela();
      return;
    }

    Long id = Long.valueOf((String) table.getValueAt(row, 0));
    String nome = (String) table.getValueAt(row, 1);
    String rg = (String) table.getValueAt(row, 3);
    String cpf = (String) table.getValueAt(row, 4);
    Residencia residencia = (Residencia) table.getValueAt(row, 5);

    Morador morador = new Morador(id, nome, dataNascimento, rg, cpf, residencia.getId());

    try {
      this.moradorController.update(morador);
      JOptionPane.showMessageDialog(this, "Morador atualizado com sucesso!");
      preencherTabela();
    } catch (Exception ex) {
      JOptionPane.showMessageDialog(this,
	      "Falha ao alterar o morador, verifique o erro abaixo: \n" + ex.getMessage(), "Erro",
	      JOptionPane.ERROR_MESSAGE);
    }
  }

  public final void preencherTabela() {
    DefaultTableModel model = (DefaultTableModel) table.getModel();
    table.setModel(model);
    table.selectAll();
    model.setRowCount(0);

    Map<Long, Morador> moradores;

    try {
      if (residenciaIdFilter == null) {
	moradores = moradorController.list();
      } else {
	moradores = moradorController.listByResidencia(residenciaIdFilter);
      }

      moradores.forEach((i, morador) -> {
	Residencia residencia;

	try {
	  if (morador.getResidenciaId() != null) {
	    residencia = this.residenciaController.getById(morador.getResidenciaId());
	  } else {
	    residencia = null;
	  }
	} catch (Exception ex) {
	  residencia = null;
	}

	Object[] data = {
	  String.valueOf(i),
	  morador.getNome(),
	  morador.getDataNascimento().toLocalDate().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")),
	  morador.getRg(),
	  morador.getCpf(),
	  residencia,};

	model.addRow(data);
      });
    } catch (Exception ex) {
      JOptionPane.showMessageDialog(this,
	      "Não foi possível realizar a conexão com o banco de dados, verifique se está ativo ou se foi configurado corretamente.",
	      "Erro", JOptionPane.ERROR_MESSAGE);
    }
  }

  public static void setResidenciaFilter(Long id) {
    residenciaIdFilter = id;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    scrollPane = new javax.swing.JScrollPane();
    table = new javax.swing.JTable();
    jPanel1 = new javax.swing.JPanel();
    btnCadastrar = new javax.swing.JButton();
    btnExcluir = new javax.swing.JButton();
    btnFaturas = new javax.swing.JButton();
    btnLimparFiltro = new javax.swing.JButton();
    btnEditar = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();

    setPreferredSize(new java.awt.Dimension(860, 547));

    scrollPane.setMinimumSize(new java.awt.Dimension(715, 16));

    table.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null, null, null}
      },
      new String [] {
        "id", "Nome", "Data de Nascimento", "RG", "CPF", "Residencia"
      }
    ) {
      Class[] types = new Class [] {
        java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
      };
      boolean[] canEdit = new boolean [] {
        false, true, true, true, true, false
      };

      public Class getColumnClass(int columnIndex) {
        return types [columnIndex];
      }

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    table.setColumnSelectionAllowed(true);
    table.getTableHeader().setReorderingAllowed(false);
    scrollPane.setViewportView(table);
    table.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    if (table.getColumnModel().getColumnCount() > 0) {
      table.getColumnModel().getColumn(0).setResizable(false);
      table.getColumnModel().getColumn(0).setPreferredWidth(50);
    }

    btnCadastrar.setText("Cadastrar");
    btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnCadastrarActionPerformed(evt);
      }
    });

    btnExcluir.setText("Excluir");
    btnExcluir.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnExcluirActionPerformed(evt);
      }
    });

    btnFaturas.setText("Faturas");
    btnFaturas.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnFaturasActionPerformed(evt);
      }
    });

    btnLimparFiltro.setText("Limpar Filtro");
    btnLimparFiltro.setActionCommand("Limpar Filtros");
    btnLimparFiltro.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnLimparFiltroActionPerformed(evt);
      }
    });

    btnEditar.setText("Editar");
    btnEditar.setToolTipText("");
    btnEditar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnEditarActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        .addContainerGap(17, Short.MAX_VALUE)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnLimparFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnFaturas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(20, 20, 20))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(20, 20, 20)
        .addComponent(btnCadastrar)
        .addGap(20, 20, 20)
        .addComponent(btnEditar)
        .addGap(20, 20, 20)
        .addComponent(btnExcluir)
        .addGap(20, 20, 20)
        .addComponent(btnFaturas)
        .addGap(20, 20, 20)
        .addComponent(btnLimparFiltro)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
    jLabel1.setText("Moradores");
    jLabel1.setMaximumSize(new java.awt.Dimension(848, 20));
    jLabel1.setMinimumSize(new java.awt.Dimension(848, 20));
    jLabel1.setPreferredSize(new java.awt.Dimension(848, 20));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, 0)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(scrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)))
    );
  }// </editor-fold>//GEN-END:initComponents

  private void btnLimparFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparFiltroActionPerformed
    residenciaIdFilter = null;
    preencherTabela();
  }//GEN-LAST:event_btnLimparFiltroActionPerformed

  private void btnFaturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFaturasActionPerformed
    int row = table.getSelectedRow();

    if (row == -1) {
      JOptionPane.showMessageDialog(this, "Selecione uma linha primeiro!", "Erro", JOptionPane.ERROR_MESSAGE);
      return;
    }

    Long id = Long.valueOf((String) table.getValueAt(row, 0));
    FaturasView.setMoradorFilter(id);

    JPanel parent = (JPanel) this.getParent();
    CardLayout layout = (CardLayout) parent.getLayout();
    layout.show(parent, "faturas");
  }//GEN-LAST:event_btnFaturasActionPerformed

  private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
    int row = table.getSelectedRow();

    if (row == -1) {
      JOptionPane.showMessageDialog(this, "Selecione uma linha primeiro!", "Erro", JOptionPane.ERROR_MESSAGE);
      return;
    }

    Long id = Long.valueOf((String) table.getValueAt(row, 0));
    EditaMoradoresView.setId(id);

    JPanel parent = (JPanel) this.getParent();
    CardLayout layout = (CardLayout) parent.getLayout();
    layout.show(parent, "editarMoradores");
  }//GEN-LAST:event_btnEditarActionPerformed

  private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCadastrarActionPerformed
    JPanel parent = (JPanel) this.getParent();
    CardLayout layout = (CardLayout) parent.getLayout();
    layout.show(parent, "cadastroMoradores");
  }// GEN-LAST:event_btnCadastrarActionPerformed

  private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnExcluirActionPerformed
    int row = table.getSelectedRow();

    if (row == -1) {
      JOptionPane.showMessageDialog(this, "Selecione uma linha primeiro!", "Erro", JOptionPane.ERROR_MESSAGE);
      return;
    }

    Long id = Long.valueOf((String) table.getValueAt(row, 0));
    Morador morador;

    try {
      morador = this.moradorController.getById(id);
    } catch (Exception ex) {
      JOptionPane.showMessageDialog(this, "O morador selecionado não existe.", "Erro", JOptionPane.ERROR_MESSAGE);
      return;
    }

    int opt = JOptionPane.showConfirmDialog(this, "Deseja realmente excluir o morador?", "Aviso",
	    JOptionPane.OK_CANCEL_OPTION);

    try {
      if (opt == 0) {
	this.moradorController.delete(morador);
	preencherTabela();
      }
    } catch (Exception ex) {
      JOptionPane.showMessageDialog(this,
	      "Falha ao excluir o morador, verifique o erro abaixo: \n" + ex.getMessage(), "Erro",
	      JOptionPane.ERROR_MESSAGE);
    }
  }// GEN-LAST:event_btnExcluirActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnCadastrar;
  private javax.swing.JButton btnEditar;
  private javax.swing.JButton btnExcluir;
  private javax.swing.JButton btnFaturas;
  private javax.swing.JButton btnLimparFiltro;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JScrollPane scrollPane;
  private javax.swing.JTable table;
  // End of variables declaration//GEN-END:variables
}
